# Import numpy as np and see the version

## Import numpy as `np` and print the version number. 

In [1]:
import numpy as np

In [3]:
print(np.__version__)

1.15.4


# How to create a 1D array?

## Create a 1D array of numbers from 0 to 9

### Step 1

In [4]:
ARRAY=np.array([0,1,2,3,4,5,6,7,8,9])
ARRAY

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Step 2

In [6]:
ARRAY1=np.arange(10)
ARRAY1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# How to create a boolean array?

## Create a 3×3 numpy array of all True’s

### Step 1

In [10]:
ARRAY2=np.full((3,3),True,dtype=bool)
ARRAY2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Step 2

In [11]:
ARRAY3=np.full((3,3),False,dtype=bool)
ARRAY3

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

# How to extract items that satisfy a given condition from 1D array?

## Extract all odd numbers from arr

In [12]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

## Extract all even numbers from arr1

In [15]:
arr1=np.array([0,1,2,3,4,5,6,7,8,9])
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr1[arr1%2==0]

array([0, 2, 4, 6, 8])

# How to replace items that satisfy a condition with another value in numpy array?

## Replace all odd numbers in arr with -1

In [19]:
arr2=np.array([0,1,2,3,4,5,6,7,8,9])
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr2[arr%2==1]=-1
arr2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# How to reshape an array?

## Convert a 1D array to a 2D array with 2 rows

### Step 1

In [24]:
ARRAY4=np.arange(10)
ARRAY4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
ARRAY4.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Step 2

In [26]:
ARRAY5=np.array([0,1,2,3,4,5,6,7,8,9])
ARRAY5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
ARRAY5.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# How to stack two arrays vertically?

## Stack arrays a and b vertically

### Step 1

In [31]:
a=np.arange(10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
b=np.repeat(1,10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
c=np.concatenate([a,b],axis=0)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Step 2

In [35]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
b=np.repeat(1,10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
c=np.vstack([a,b])
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Step 3

In [38]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
b=np.repeat(1,10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [40]:
c=np.r_[a,b]
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# How to stack two arrays horizontally?

## Stack the arrays a and b horizontally. 

### Step 1

In [41]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
b=np.repeat(1,10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [43]:
c=np.concatenate([a,b],axis=1)
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### Step 2

In [44]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
b=np.repeat(1,10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
c=np.hstack([a,b])
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### Step3

In [47]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
b=np.repeat(1,10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [51]:
c=np.c_[a,b]
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# How to get the common items between two python numpy arrays?

## Get the common items between a and b

In [52]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [53]:
b = np.array([7,2,10,2,7,4,9,4,9,8])
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [58]:
c=np.intersect1d(a,b)
c

array([2, 4])

# How to remove from one array those items that exist in another?

## array a remove all items present in array b

In [59]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [60]:
b = np.array([5,6,7,8,9])
b

array([5, 6, 7, 8, 9])

In [61]:
c=np.setdiff1d(a,b)
c

array([1, 2, 3, 4])

# How to get the positions where elements of two arrays match?

## Get the positions where elements of a and b match

In [62]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [63]:
b = np.array([7,2,10,2,7,4,9,4,9,8])
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [64]:
c=np.where(a==b)
c

(array([1, 3, 5, 7], dtype=int64),)

# How to extract all numbers between a given range from a numpy array?

##  Get all items between 5 and 10 from a

### Step 1

In [65]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a

array([ 2,  6,  1,  9, 10,  3, 27])

In [76]:
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

### Step 2

In [77]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a

array([ 2,  6,  1,  9, 10,  3, 27])

In [81]:
index1=np.where(np.logical_and(a>=5,a<=10))
a[index1]

array([ 6,  9, 10])

### Step 3

In [82]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a

array([ 2,  6,  1,  9, 10,  3, 27])

In [83]:
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])